-- Generated by scripts/compute-route-legs.mjs. Walking legs from OSRM (FOSSGIS foot profile).
-- Re-run the script after changing a route's stops.

update route_venues rv set
  leg_geometry = '[[10.760146,59.918343],[10.760203,59.918288],[10.760248,59.918248],[10.760125,59.91821],[10.759998,59.918178],[10.759914,59.918165],[10.759806,59.918166],[10.759729,59.918174],[10.759667,59.918192],[10.759641,59.918202],[10.759573,59.918232],[10.759525,59.918272],[10.759497,59.918318],[10.759483,59.918378],[10.759479,59.918552],[10.759428,59.918553],[10.759399,59.918553],[10.759369,59.918553],[10.759342,59.918553],[10.759304,59.918553],[10.759279,59.918553],[10.759272,59.918572],[10.759257,59.918593],[10.759218,59.918602],[10.759185,59.918605],[10.758827,59.918608],[10.758485,59.91861],[10.758047,59.918613],[10.757676,59.918614],[10.757591,59.918611],[10.757537,59.918605],[10.757532,59.918616],[10.757514,59.918657],[10.757496,59.918696],[10.757499,59.918706],[10.75744,59.918729],[10.757443,59.91893]]'::jsonb,
  leg_distance_m = 241,
  leg_duration_s = 193,
  leg_steps = '[{"type":"depart","modifier":null,"name":null,"distance":12,"duration":10,"location":[10.760146,59.918343]},{"type":"turn","modifier":"right","name":null,"distance":79,"duration":63,"location":[10.760248,59.918248]},{"type":"turn","modifier":"left","name":null,"distance":11,"duration":9,"location":[10.759479,59.918552]},{"type":"end of road","modifier":"right","name":null,"distance":5,"duration":4,"location":[10.759279,59.918553]},{"type":"turn","modifier":"left","name":null,"distance":97,"duration":77,"location":[10.759257,59.918593]},{"type":"turn","modifier":"right","name":null,"distance":16,"duration":13,"location":[10.757537,59.918605]},{"type":"turn","modifier":"right","name":null,"distance":22,"duration":18,"location":[10.75744,59.918729]},{"type":"arrive","modifier":null,"name":null,"distance":0,"duration":0,"location":[10.757443,59.91893]}]'::jsonb
from routes r, venues v
where rv.route_id = r.id and rv.venue_id = v.id
  and r.city = 'Oslo' and r.slug = 'loekka-paa-langs'
  and v.name = 'Territoriet';

update route_venues rv set
  leg_geometry = '[[10.757443,59.91893],[10.757446,59.919094],[10.757457,59.919104],[10.757456,59.919116],[10.757456,59.919157],[10.757455,59.919196],[10.757454,59.919209],[10.757439,59.919705],[10.757452,59.920063],[10.757478,59.920077],[10.757478,59.92008],[10.75748,59.920117],[10.757482,59.920159],[10.757429,59.920184],[10.757461,59.920645],[10.757473,59.921036],[10.757473,59.921045],[10.757476,59.921096],[10.757477,59.921131],[10.757478,59.921135],[10.757472,59.921159],[10.757449,59.92151],[10.757432,59.92228],[10.757431,59.922303],[10.757491,59.922316],[10.757545,59.922318],[10.757545,59.922327],[10.757545,59.922351],[10.757546,59.92239],[10.757546,59.922403],[10.757572,59.92248],[10.757518,59.922516],[10.757506,59.922699],[10.757491,59.922901],[10.757472,59.923222],[10.757462,59.923357],[10.757439,59.923377],[10.757437,59.92339],[10.757434,59.923414],[10.757432,59.923431],[10.75743,59.923439],[10.758359,59.923434]]'::jsonb,
  leg_distance_m = 563,
  leg_duration_s = 451,
  leg_steps = '[{"type":"depart","modifier":null,"name":null,"distance":129,"duration":103,"location":[10.757443,59.91893]},{"type":"turn","modifier":"left","name":null,"distance":13,"duration":11,"location":[10.757478,59.920077]},{"type":"turn","modifier":"right","name":null,"distance":236,"duration":189,"location":[10.757429,59.920184]},{"type":"end of road","modifier":"right","name":null,"distance":7,"duration":5,"location":[10.757431,59.922303]},{"type":"turn","modifier":"left","name":null,"distance":18,"duration":15,"location":[10.757545,59.922318]},{"type":"turn","modifier":"left","name":null,"distance":108,"duration":87,"location":[10.757572,59.92248]},{"type":"turn","modifier":"right","name":null,"distance":52,"duration":42,"location":[10.75743,59.923439]},{"type":"arrive","modifier":"left","name":null,"distance":0,"duration":0,"location":[10.758359,59.923434]}]'::jsonb
from routes r, venues v
where rv.route_id = r.id and rv.venue_id = v.id
  and r.city = 'Oslo' and r.slug = 'loekka-paa-langs'
  and v.name = 'Parkteatret';

update route_venues rv set
  leg_geometry = '[[10.758359,59.923434],[10.759028,59.923431],[10.759075,59.923431],[10.759094,59.923435],[10.759109,59.923442],[10.759118,59.923451],[10.759122,59.923467],[10.759176,59.923466],[10.759208,59.923466],[10.759233,59.923466],[10.759347,59.923466],[10.759338,59.923957],[10.759329,59.924479],[10.759332,59.924506],[10.759332,59.924519],[10.759332,59.924527],[10.759332,59.924553],[10.759331,59.924586],[10.759331,59.924599],[10.759323,59.924619],[10.759302,59.924999]]'::jsonb,
  leg_distance_m = 229,
  leg_duration_s = 183,
  leg_steps = '[{"type":"depart","modifier":"left","name":null,"distance":40,"duration":32,"location":[10.758359,59.923434]},{"type":"turn","modifier":"left","name":null,"distance":5,"duration":4,"location":[10.759075,59.923431]},{"type":"turn","modifier":"right","name":null,"distance":13,"duration":10,"location":[10.759122,59.923467]},{"type":"turn","modifier":"left","name":null,"distance":171,"duration":137,"location":[10.759347,59.923466]},{"type":"arrive","modifier":null,"name":null,"distance":0,"duration":0,"location":[10.759302,59.924999]}]'::jsonb
from routes r, venues v
where rv.route_id = r.id and rv.venue_id = v.id
  and r.city = 'Oslo' and r.slug = 'loekka-paa-langs'
  and v.name = 'Grünerløkka Brygghus';

update route_venues rv set
  leg_geometry = '[[10.759302,59.924999],[10.759291,59.925199]]'::jsonb,
  leg_distance_m = 22,
  leg_duration_s = 18,
  leg_steps = '[{"type":"depart","modifier":null,"name":null,"distance":22,"duration":18,"location":[10.759302,59.924999]},{"type":"arrive","modifier":null,"name":null,"distance":0,"duration":0,"location":[10.759291,59.925199]}]'::jsonb
from routes r, venues v
where rv.route_id = r.id and rv.venue_id = v.id
  and r.city = 'Oslo' and r.slug = 'loekka-paa-langs'
  and v.name = 'Bar Boca';

update route_venues rv set
  leg_geometry = '[[10.750882,59.914661],[10.750915,59.914648],[10.750946,59.914636],[10.751424,59.9144],[10.751444,59.914388],[10.751564,59.914283]]'::jsonb,
  leg_distance_m = 57,
  leg_duration_s = 46,
  leg_steps = '[{"type":"depart","modifier":"right","name":null,"distance":57,"duration":46,"location":[10.750882,59.914661]},{"type":"arrive","modifier":null,"name":null,"distance":0,"duration":0,"location":[10.751564,59.914283]}]'::jsonb
from routes r, venues v
where rv.route_id = r.id and rv.venue_id = v.id
  and r.city = 'Oslo' and r.slug = 'torggata-runden'
  and v.name = 'Himkok';

update route_venues rv set
  leg_geometry = '[[10.751564,59.914283],[10.751444,59.914388],[10.751424,59.9144],[10.750946,59.914636],[10.750957,59.914642],[10.751002,59.914668],[10.751057,59.914702],[10.75107,59.914709],[10.751068,59.914718],[10.751072,59.914728],[10.751086,59.914742],[10.751567,59.915062],[10.75156,59.915066],[10.751501,59.915104],[10.751574,59.915142],[10.751639,59.915172],[10.751782,59.91523],[10.751728,59.915268],[10.751717,59.915281],[10.751773,59.915299],[10.751928,59.915364],[10.752283,59.915514],[10.752439,59.915579],[10.752459,59.915591],[10.752468,59.915604],[10.752485,59.915603],[10.752489,59.915604],[10.752599,59.915639],[10.752692,59.915669],[10.752709,59.915675],[10.752697,59.915679],[10.752686,59.915684],[10.752456,59.915864],[10.752115,59.916071]]'::jsonb,
  leg_distance_m = 273,
  leg_duration_s = 221,
  leg_steps = '[{"type":"depart","modifier":null,"name":null,"distance":53,"duration":42,"location":[10.751564,59.914283]},{"type":"turn","modifier":"right","name":null,"distance":59,"duration":47,"location":[10.750946,59.914636]},{"type":"end of road","modifier":"left","name":null,"distance":6,"duration":5,"location":[10.751567,59.915062]},{"type":"turn","modifier":"right","name":"Calmeyers gate","distance":21,"duration":19,"location":[10.751501,59.915104]},{"type":"turn","modifier":"left","name":null,"distance":7,"duration":6,"location":[10.751782,59.91523]},{"type":"turn","modifier":"right","name":null,"distance":56,"duration":45,"location":[10.751717,59.915281]},{"type":"end of road","modifier":"right","name":null,"distance":1,"duration":1,"location":[10.752468,59.915604]},{"type":"turn","modifier":"left","name":null,"distance":70,"duration":56,"location":[10.752485,59.915603]},{"type":"arrive","modifier":null,"name":null,"distance":0,"duration":0,"location":[10.752115,59.916071]}]'::jsonb
from routes r, venues v
where rv.route_id = r.id and rv.venue_id = v.id
  and r.city = 'Oslo' and r.slug = 'torggata-runden'
  and v.name = 'Torggata Botaniske';

update route_venues rv set
  leg_geometry = '[[10.752115,59.916071],[10.751998,59.916142],[10.751941,59.916181],[10.751936,59.91619],[10.751937,59.9162],[10.751941,59.916207],[10.751966,59.916222],[10.751953,59.916229],[10.751924,59.916242],[10.752995,59.916832],[10.753092,59.916884],[10.753192,59.916938],[10.753172,59.91695],[10.753133,59.916973],[10.753162,59.916985],[10.753468,59.917153]]'::jsonb,
  leg_distance_m = 162,
  leg_duration_s = 129,
  leg_steps = '[{"type":"depart","modifier":null,"name":null,"distance":16,"duration":12,"location":[10.752115,59.916071]},{"type":"turn","modifier":"right","name":null,"distance":5,"duration":4,"location":[10.751941,59.916181]},{"type":"turn","modifier":"left","name":null,"distance":3,"duration":3,"location":[10.751966,59.916222]},{"type":"turn","modifier":"right","name":"Torggata","distance":105,"duration":84,"location":[10.751924,59.916242]},{"type":"turn","modifier":"left","name":null,"distance":5,"duration":4,"location":[10.753192,59.916938]},{"type":"turn","modifier":"right","name":null,"distance":28,"duration":22,"location":[10.753133,59.916973]},{"type":"arrive","modifier":null,"name":null,"distance":0,"duration":0,"location":[10.753468,59.917153]}]'::jsonb
from routes r, venues v
where rv.route_id = r.id and rv.venue_id = v.id
  and r.city = 'Oslo' and r.slug = 'torggata-runden'
  and v.name = 'Crowbar & Bryggeri';

update route_venues rv set
  leg_geometry = '[[10.753468,59.917153],[10.754203,59.917557],[10.754219,59.91757],[10.754228,59.917587]]'::jsonb,
  leg_distance_m = 66,
  leg_duration_s = 52,
  leg_steps = '[{"type":"depart","modifier":null,"name":null,"distance":66,"duration":52,"location":[10.753468,59.917153]},{"type":"arrive","modifier":null,"name":null,"distance":0,"duration":0,"location":[10.754225,59.917595]}]'::jsonb
from routes r, venues v
where rv.route_id = r.id and rv.venue_id = v.id
  and r.city = 'Oslo' and r.slug = 'torggata-runden'
  and v.name = 'Café Sara';
